import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/ui/NavBar";
import MobileNav from "@/ui/MobileNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Store Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col   max-w-7xl mx-auto">
        <div className="bg-[#d2f9e6]  ">
          <NavBar />
          <div className="relative z-10 px-2 my-2 md:pb-0 pb-20 text-black">{children}</div>
          <MobileNav />
        </div>
      </body>
    </html>
  );
} 
